name: squealer lint
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - uses: actions/setup-go@v3
      with:
        go-version-file: ./go.mod
        
    - run: go version

    - name: Lint
      run: make quality
